version: '3'

services:
  clustering:
    build:
      context: ./
    container_name: clustering
    environment:
      PORT: 3006
      # NEO4J_PASSWORD: password
      # NEO4J_USE_ENCRYPTION: 'false'
      # NEO4J_URI: bolt://neo4j:7687
      # NEO4J_USER: neo4j
      # CC_URL: http://command_core:3003
      # CLOUDAMQP_URL: amqp://guest:guest@ab_rabbit
    volumes:
      - ./:/app
